name: test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - "**"

env:
  workspace: ownership

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]

    runs-on: ${{ matrix.os }}-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run Clippy on Derive
        run: cargo clippy --package ${{ env.workspace }}-derive

      - name: Run clippy
        run: cargo clippy --package ${{ env.workspace }}

      - name: Run tests
        run: cargo test --package ${{ env.workspace }} --all-features
